### ISSUE TITLE
The local run failed

### ISSUE THREAD

**Issue by justforhing** [yadavrajsky/Blockchain-Based-Incentivized-Authentication-System#1]
Can you provide the specific version of the software required for the local running environment?
here is mine:
Truffle v5.11.5 (core: 5.11.5)
Ganache v7.9.1
Solidity v0.5.16 (solc-js)
Node v18.20.2
Web3.js v1.10.0
 
tips：
➜  blockchain git:(main) ✗ truffle migrate

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

Starting migrations...
======================
> Network name:    'development'
> Network id:      5777
> Block gas limit: 6721975 (0x6691b7)

1_deploy_auth_service_provider.js
=================================

   Deploying 'AuthenticationServiceProvider'
   -----------------------------------------
 *** Deployment Failed ***

"AuthenticationServiceProvider" hit an invalid opcode while deploying. Try:
   * Verifying that your constructor params satisfy all assert conditions.
   * Verifying your constructor code doesn't access an array out of bounds.
   * Adding reason strings to your assert statements.

Exiting: Review successful transactions manually by checking the transaction hashes above on Etherscan.

Error:  *** Deployment Failed ***

"AuthenticationServiceProvider" hit an invalid opcode while deploying. Try:
   * Verifying that your constructor params satisfy all assert conditions.
   * Verifying your constructor code doesn't access an array out of bounds.
   * Adding reason strings to your assert statements.

    at /opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:330:1
Truffle v5.11.5 (core: 5.11.5)
Node v18.20.2

**Comment by yadavrajsky** [comment]
### Update Solidity Version in Contracts

All contracts within the `blockchain/contracts` directory should be updated explicitly  to the Solidity version as `0.8.0`. Here is an example header for the contracts:

```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity 0.8.0;
```
### Truffle Configuration

The Truffle configuration file (`truffle-config.ts`) should be modified to use the Solidity compiler version `0.8.0`. Below is the updated compiler configuration:

```ts
// truffle-config.ts
// Configure your compilers
compilers: {
  solc: {
    version: "0.8.0",      // Fetch exact version from solc-bin (default: Truffle's version)
  }
},
```
