### ISSUE TITLE
login problems

### ISSUE THREAD

**Issue by justforhing** [yadavrajsky/Blockchain-Based-Incentivized-Authentication-System#2]
Why can I log in successfully with a password that I didn't use when I registered, please help me to see

**Comment by yadavrajsky** [comment]
It should work. Make sure your database is configured properly i.e. mongodb is running.

**Comment by justforhing** [comment]
I looked at the source code and saw that the password was not recorded in the database, was that true?
![Uploading Xnip2024-05-25_17-29-09.jpg…]()

**Comment by justforhing** [comment]
![Xnip2024-05-25_17-29-09](https://github.com/yadavrajsky/Blockchain-Based-Incentivized-Authentication-System/assets/34234023/848246bd-2a24-4688-a46c-c5d4ec77b65a)

**Comment by yadavrajsky** [comment]
Yes that is true. Few codes are boilerplate for further enhancement in future. This is just a demo. I have now fixed everything regarding login issue . Issue was that backend was not  passing its wallet address while calling ABI of the smart contract and few BigInt glitches. Now I have updated to Hardhat for contract deployment and also updated to latest packages.
